title: PE25
locale: en_US
logo:
tagline: coding experiments 101
descritpion: The trials and tribulations of a novice coder.
owner: PE25
name: PE
github: pe25
google:
    verify:

theme: jekyll-theme-architect
url: "https://pe25.github.io"

Author: PE

author's home: "https://pe25.github.io"
