title: PE25
tagline: coding experiments 101
descritpion: The trials and tribulations of a novice coder.
theme: jekyll-theme-architect
url: "https://pe25.github.io"
title: PE25
Author: PE
github: PE25
author's home: "https://pe25.github.io"
